### ISSUE TITLE
vector::_M_range_check: __n (which is 49392123881) >= this->size() (which is 396)

### ISSUE THREAD

**Issue by vahid-sohrabloo** [mcufont/mcufont#2]
this error happen when I want to convert my font.
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 49392123881) >= this->size() (which is 396)
mcufont bwfont_export DroidNaskh10bw.dat DroidNaskh10.c

I use this font
http://fonts.gstatic.com/ea/droidarabicnaskh/v7/download.zip

**Comment by PetteriAimonen** [comment]
Should be fixed now, sorry it took so long.
