### ISSUE TITLE
Render font shifted at 1/3 pixel

### ISSUE THREAD

**Issue by denys-potapov** [mcufont/mcufont#24]
Can i encode the font shifted by 1/3 pixel? I want to make the sub-pixel rendering with mcufont. My current idea is make 3 different fonts (for Red Green and Blue) and mix them on output. So the question is how to encode the font shifted by +1/3 and -1/3 pixel.

Probably you can just tell me what function I need to patch to build my custom encoder? Thanks in advance.

**Comment by PetteriAimonen** [comment]
It would probably be in LoadFreetype() in `encoder/freetype_import.cc`. It would need some freetype call that can offset the rendering by subpixel amount.

But I think a better approach could be to tell freetype somehow to stretch the font 3x in horizontal direction, and encode it as a single font. Then when rendering, just put the different pixels as subpixel colors. That should compress better and is probably also easier to implement.

**Comment by denys-potapov** [comment]
Thanks for the idea. Will try to do.
