### ISSUE TITLE
undefined reference

### ISSUE THREAD

**Issue by Blackend** [mcufont/mcufont#27]
Maybe I can fix it, but I wish it could work from the hand :|

```ld: build/test1.o: in function `entry':
test1.c:(.text+0x465): undefined reference to `mf_render_aligned'
ld: build/test1.o: in function `char_callback':
test1.c:(.text+0x4c8): undefined reference to `mf_render_character'
ld: build/test1.o:(.data.rel.ro+0x38): undefined reference to `mf_rlefont_character_width'
ld: build/test1.o:(.data.rel.ro+0x40): undefined reference to `mf_rlefont_render_character'```

**Comment by PetteriAimonen** [comment]
It sounds like you are including the `mcufont.h` header, but the `.c` files such as `mf_rlefont.c` are not included in the compilation.

**Comment by Blackend** [comment]
that way i was able to compile code, now i need to find out why its freezing :) but that my problem ;)

```
	// #include	"fonts.h"
	#include	"mf_font.c"
	#include	"mf_rlefont.c"
	// #include	"mf_encoding.c"
	#include	"mf_justify.c"
	// #include	"mf_wordwrap.c"
	#include	"mf_kerning.c"
	#include	"mf_encoding.c"
	#include	"mcufont.h"
```

**Comment by Blackend** [comment]
Thank You for the point :) (small error from my side fixed, and this is result)

![image](https://user-images.githubusercontent.com/53617677/165167945-c7e49c5f-61f6-4501-97fb-a90c33621eda.png)

Can I made this font more thin?

**Comment by Blackend** [comment]
Thank You again, very good source :)

https://blackdev.org/shot/1897.mkv
