### ISSUE TITLE
absolute path, draw pixel

### ISSUE THREAD

**Issue by Blackend** [mcufont/mcufont#29]
# Hey!

I can't understand why there is problem with pixel drawing.

### working example (original code):
```
/* Call the callback to write one pixel to screen, and advance to next
 * pixel position. */
static void write_pixels(struct renderstate_r *rstate, uint16_t count,
                         uint8_t alpha)
{
    [...] // i don't use word-wrap

    /* Write the remaining part */
    if (count)
    {
        rstate->callback(rstate->x, rstate->y, count, alpha, rstate->state);
        rstate->x += count;
    }
}
```

effect:
![image](https://user-images.githubusercontent.com/53617677/166472492-fcd35e7f-b754-412d-9aad-39431c303b42.png)

### modified:
changed *rstate->callback* to *lib_font_pixel_put*
```
    [...] // i don't use word-wrap

    /* Write the remaining part */
    if (count)
    {
        lib_font_pixel_put(rstate->x, rstate->y, count, alpha, rstate->state);
        rstate->x += count;
    }
}
```

effect:
![image](https://user-images.githubusercontent.com/53617677/166473020-7207d66a-7a75-4f91-906a-85d6a64825c8.png)

### Both **rstate->callback** and **lib_font_pixel_put** are the same function.

```
static void lib_font_pixel_put(int16_t x, int16_t y, uint8_t count, uint8_t alpha, void *state)
    {
    while (count--)
        {
            data[ (y * lib_font_properties.scanline_pixel) + x ] = lib_color_alpha( data[ (y * lib_font_properties.scanline_pixel) + x ], lib_font_properties.color, alpha );
            x++;
        }
    }

static uint8_t lib_font_char(int16_t x0, int16_t y0, mf_char character, void *state)
    {
        return mf_render_character(&mf_rlefont_DejaVuSans12.font, x0, y0, character, &lib_font_pixel_put, state);
    }

        mf_render_aligned(
            &mf_rlefont_DejaVuSans12.font,
            0, 0,
            MF_ALIGN_LEFT,
            "Hello, World!", 13,
            &lib_font_char, NULL);
```

**Comment by PetteriAimonen** [comment]
The callback is not always `lib_font_pixel_put()`, the justification routines use it for other purposes.

The mcufont decoder library relies quite heavily on function pointers and callbacks, and I do not think it is reasonable to try to remove them from the code. The overhead of function pointers is quite low on most platforms.
