### ISSUE TITLE
How to render unicode fonts

### ISSUE THREAD

**Issue by supreme-shivam** [mcufont/mcufont#35]
I have tried to render unicode font but it didn't work, I have to convert unicode to ASCII values to render and it not possible to render all characters in the right way, and there is no doc or example for this, can you please help me in this. And font exporting for unicode font.
Thank you.

**Comment by PetteriAimonen** [comment]
mcufont uses utf-8 for input of unicode characters.

**Comment by supreme-shivam** [comment]
Couldn't get it can you explain please.
