### ISSUE TITLE
The issue with rendering DSEG7 classic bold font with height 48px

### ISSUE THREAD

**Issue by HexRx** [mcufont/mcufont#40]
Hi, I tried to convert and then render the font DSEG7 Classic Bold (https://www.keshikan.net/fonts-e.html) with 48px size (btw 72px looks correct) and I got some rendering issues:

## Incorrect: mcufont rendering 48px
![mcufont_render_48px_issue](https://github.com/user-attachments/assets/44d0d343-dcaf-4db5-bba0-db6603574476)
the same image with the zoom:
![mcufont_render_48px_issue_zoom](https://github.com/user-attachments/assets/eb3610e0-58aa-4676-be94-d6d09345b327)
highlighted issues in the image above:
- elements in red circles should have vertical gaps
- elements in blue circles shouldn't have 2 pixel gaps, only 1 pixel

the output of mcufont cli tool with options `mcufont show_glyph DSEG7Classic-Bold48bw.dat 15`
```
Width: 39
Chars: 65 97 
...........XXXXXXXXXXXXXXXXXXXXXXX...
..........XXXXXXXXXXXXXXXXXXXXXXXXX..
.........X.XXXXXXXXXXXXXXXXXXXXXXX...
........XXX.XXXXXXXXXXXXXXXXXXXXX..XX
........XXXX.XXXXXXXXXXXXXXXXXXX..XXX
........XXXXX.XXXXXXXXXXXXXXXXX..XXXX
........XXXXXX..................XXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX..................XXXXX
........XXXXX.XXXXXXXXXXXXXXXXX..XXXX
........XXXX.XXXXXXXXXXXXXXXXXXX..XXX
........XXX.XXXXXXXXXXXXXXXXXXXXX..XX
........XXX.XXXXXXXXXXXXXXXXXXXXX....
........XXXX.XXXXXXXXXXXXXXXXXXX..XXX
........XXXXX.XXXXXXXXXXXXXXXXX..XXXX
........XXXXXX..................XXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX.................XXXXXX
........XXXXXX..................XXXXX
........XXXXX....................XXXX
........XXXX......................XXX
........XXX........................XX
.........X...........................
.....................................
.....................................
```
## Correct: original TTF rendering 48px
![ttf_48](https://github.com/user-attachments/assets/4f19ae82-4a9d-4098-a580-d675ef2f089e)
the same image with the zoom:
![ttf_48_zoom](https://github.com/user-attachments/assets/5db1aa01-a1e7-4769-ad0e-74cfc529fc42)

## Correct: mcufont rendering 72px
![mcufont_render_72px_correct](https://github.com/user-attachments/assets/4f489325-fe09-4db3-89a2-ca4ef74b23c1)
the same image with the zoom:
![mcufont_render_72px_correct_zoom](https://github.com/user-attachments/assets/80255b4b-a8bc-4e70-b6e0-0a51998d3ef7)

I used the code from the mcufont repository with the last commit: 96fc7d67d0e35855844a70f2153a8f9275d279f4
TTF font DSEG7Classic-Bold.ttf  was converted using the commands:
```
mcufont import_ttf DSEG7Classic-Bold.ttf 48 bw
mcufont filter DSEG7Classic-Bold48bw.dat 0-255 0x2010-0x2015
mcufont rlefont_optimize DSEG7Classic-Bold48bw.dat 50
mcufont rlefont_export DSEG7Classic-Bold48bw.dat
```

Thanks for any suggestion!

I'm also working on an online font convert tool for mcufont library: https://hexrx.github.io/mcufont-converter-web/

**Comment by PetteriAimonen** [comment]
That's probably somehow related to freetype hinting mode.

**Comment by HexRx** [comment]
Thank you for quick reply and interesting suggestion, possibly I should try other interpreter :thinking:  https://freetype.org/freetype2/docs/reference/ft2-properties.html#tt_interpreter_version_xxx

**Comment by HexRx** [comment]
The issue seems to be related to `bw` option for command `mcufont import_ttf`
Without `bw` option the gaps look better:
![Screenshot from 2024-08-06 22-02-47](https://github.com/user-attachments/assets/68be7a37-4cbc-4476-9b1f-0ce89db3c7e8)

Thanks! I'm going to close the topic.

**Comment by PetteriAimonen** [comment]
Yeah, currently [bw mode forces FT_LOAD_TARGET_MONO](https://github.com/mcufont/mcufont/blob/master/encoder/freetype_import.cc#L108C20-L108C39) which uses a [stronger hinting algorithm](https://freetype.org/freetype2/docs/reference/ft2-glyph_retrieval.html#ft_load_target_xxx). In general this results in better bw rendering, but apparently not for all fonts.
